### ISSUE TITLE
Use JavaScript modules in the browser

### ISSUE THREAD

**Issue by MaybeThisIsRu** [MaybeThisIsRu/smix-eleventy-starter#35]
https://caniuse.com/es6-module

Browser support is fairy good. We can reduce complexity by using ES6 modules directly instead of bundling them up with Browserify. I'd be interested in hearing what the community thinks! Is it too soon for such a change?

---

- [x] Remove gulp's js task.
- [x] Use another transpiler directly (babel/snowpack/rollup/esbuild)
- [x] Ensure there's a nice way to include JS files in templates on a per-page and a global basis.

**Comment by hirusi** [comment]
- [ ] Update gulp's `js` task to only transpile ES2015/ES6 to ES5.
- [ ] Use [Eleventy's passthrough process](https://www.11ty.dev/docs/copy/) to copy JavaScript files as-is.
- [ ] Ensure there's a nice way to include JS files in templates on a per-page and a global basis.
