### ISSUE TITLE
Remove gulp to rely entirely on Eleventy

### ISSUE THREAD

**Issue by MaybeThisIsRu** [MaybeThisIsRu/smix-eleventy-starter#42]
Gulp while nice is just one more added complexity. It would be great to remove it and rely on Eleventy entirely. This also aids in #35 by setting up a foundation for it.

**Comment by darekkay** [comment]
One data point - I've explicitly decided against reimplementing my build pipeline in Eleventy. I've created a [@darekkay/gulp](https://github.com/darekkay/darekkay-gulp) package that is independent of other frameworks. It's a little bit slower and requires running gulp and 11ty at the same time, but I can use it with many other non-11ty projects. YMMV.

**Comment by miklb** [comment]
> I think my CSS and JS tasks are light enough (or will be) to remove gulp and rely on some npm binaries directly.

I discovered `postcss style.css -w -m -o min.style.css` in a script left my Gulp tasks obsolete. I also use a `postcss.config.js` I'll check #23 and see where I can help. I loved everything else I read about the project. Especially seeing the recent activity after reading the goodbye post.

**Comment by hirusi** [comment]
`html`, `font`, `js` tasks are now no longer reliant on `gulp`.

We are left with images (I understand @darekkay's method does not require gulp) and CSS (big question mark on purging and minification for production -- otherwise `postcss` can be used with an npm script).

**Comment by miklb** [comment]
CSS nano can be run inside the PostCSS config for minification. I’m making a huge assumption that PostCSS can run before Eleventy passes the CSS file through to the build directory which I also blindly assume handles overwriting the file(s). I’m looking forward to digging into things deeper soon.

**Comment by MaybeThisIsRu** [comment]
Purge is a separate tool, however, to PostCSS. I suppose we should be able to use its npm binary as an npm script that is only run on `prod`.

Eleventy too can be run via npm scripts just fine.

We're just left to ponder about images. I'll email @darekkay. :)
