### ISSUE TITLE
Add a search capability

### ISSUE THREAD

**Issue by MaybeThisIsRu** [MaybeThisIsRu/smix-eleventy-starter#47]
Zero ideas on this one. Placeholder for now.

**Comment by arpitbatra123** [comment]
I think this should be possible via https://lunrjs.com/ , by doing something like this - https://www.raymondcamden.com/2019/10/20/adding-search-to-your-eleventy-static-site-with-lunr . Also, Algolia, seems to be a nice solution as well, and that is what's being used currently on https://www.raymondcamden.com/search/

**Comment by MaybeThisIsRu** [comment]
Lunr looks good. I wonder if anyone has made a package/plugin out of this for Eleventy...

**Comment by MaybeThisIsRu** [comment]
@hugomd raised https://stork-search.net/ on Mastodon, and that looks even better!

**Comment by MaybeThisIsRu** [comment]
I probably won't be going ahead with this. Feels too complex. Even Lunr and similar solutions.
